version: '3.8'

services:
  nginx:
    image: nginx
    volumes:
    # - ./templates:/etc/nginx/templates
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./cache:/data/nginx/cache
    # - ./images:/www/data/images
    ports:
    - "8080:80"
    environment:
    - NGINX_PORT=80

  backend:
    container_name: nodejs
    restart: always
    build: ./
    volumes:
     - ./nodejs-app/public:/usr/src/app/public
    ports:
      - "4000:4000"